# Generated by Django 2.1.1 on 2018-10-08 20:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='arrecadacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('tipo_taxa', models.IntegerField(choices=[(1, 'TAH'), (2, 'CFEM')], default=1)),
                ('tipo_atv', models.IntegerField(choices=[(1, 'Água Mineral/Potável'), (2, 'Calcário'), (3, 'Calcário Calcítico'), (4, 'Calcário Dolomítico'), (5, 'Água Termal'), (6, 'Granito/Brita'), (7, 'Minério de Manganês'), (8, 'Minério de Ouro/Ouro'), (9, 'Gema/Diamantes'), (10, 'Argila'), (11, 'Areia')], default=1)),
                ('ano', models.IntegerField(choices=[(1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018)),
            ],
        ),
        migrations.CreateModel(
            name='cidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='demografico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('populacao_urbana', models.IntegerField()),
                ('populacao_rural', models.IntegerField()),
                ('ano', models.IntegerField(choices=[(1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018)),
                ('cidades_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='map.cidades')),
            ],
        ),
        migrations.CreateModel(
            name='economia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pib_pc', models.FloatField(null=True)),
                ('receitas_fontext', models.FloatField(null=True)),
                ('receitas', models.FloatField(null=True)),
                ('despesas', models.FloatField(null=True)),
                ('pop_ativa_18mais', models.IntegerField(null=True)),
                ('ocup_agropecuario', models.FloatField(null=True)),
                ('ocup_comercio', models.FloatField(null=True)),
                ('ocup_construcao', models.FloatField(null=True)),
                ('ocup_mineral', models.FloatField(null=True)),
                ('ocup_industria_utilpub', models.FloatField(null=True)),
                ('ocup_servic', models.FloatField(null=True)),
                ('ocup_industria_transf', models.FloatField(null=True)),
                ('ocup_grau_form', models.FloatField(null=True)),
                ('ocup_fundamental', models.FloatField(null=True)),
                ('ocup_medio', models.FloatField(null=True)),
                ('ocup_superior', models.FloatField(null=True)),
                ('atv_1maior_valor', models.IntegerField(null=True)),
                ('atv_2maior_valor', models.IntegerField(null=True)),
                ('atv_3maior_valor', models.IntegerField(null=True)),
                ('ano', models.IntegerField(choices=[(1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018)),
                ('cidades_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='map.cidades')),
            ],
        ),
        migrations.CreateModel(
            name='mesorregioes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='microrregioes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='operacao_empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('ano', models.IntegerField(choices=[(1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018)),
            ],
        ),
        migrations.CreateModel(
            name='pessoa_fisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=13, unique=True)),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='pessoa_juridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('razaosocial', models.CharField(max_length=150)),
                ('nomefantasia', models.CharField(max_length=150)),
                ('atividade_mineradora', models.IntegerField()),
                ('cooperativa', models.BooleanField()),
                ('cidades_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='map.cidades')),
            ],
        ),
        migrations.CreateModel(
            name='socioeconomico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pop_ocupada', models.IntegerField(null=True)),
                ('idhm', models.FloatField(null=True)),
                ('idhm_renda', models.FloatField(null=True)),
                ('idhm_longevidade', models.FloatField(null=True)),
                ('idhm_educacao', models.FloatField(null=True)),
                ('expc_vida', models.FloatField(null=True)),
                ('prob_60anos', models.FloatField(null=True)),
                ('expc_anos_estudo18', models.FloatField(null=True)),
                ('renda_pc', models.FloatField(null=True)),
                ('salario_trab_form', models.FloatField(null=True)),
                ('prop_extr_pobre', models.FloatField(null=True)),
                ('prop_pobre', models.FloatField(null=True)),
                ('prop_vuln_pobre', models.FloatField(null=True)),
                ('taxa_analfab_15mais', models.FloatField(null=True)),
                ('ideb_inicias', models.FloatField(null=True)),
                ('ideb_finais', models.FloatField(null=True)),
                ('perc_pop_agua_enc', models.FloatField(null=True)),
                ('perc_pop_coleta_lixo', models.FloatField(null=True)),
                ('perc_pop_eletricidade', models.FloatField(null=True)),
                ('esg_sanit_adequado', models.FloatField(null=True)),
                ('perc_pop_esg_inadequado', models.FloatField(null=True)),
                ('perc_urban_vias_public', models.FloatField(null=True)),
                ('ano', models.IntegerField(choices=[(1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018)),
                ('cidades_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='map.cidades')),
            ],
        ),
        migrations.CreateModel(
            name='titulos_minerarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('ano', models.IntegerField(choices=[(1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018)),
                ('fase', models.CharField(max_length=254, null=True)),
                ('ult_evento', models.CharField(max_length=254)),
                ('nome_prop', models.CharField(max_length=254)),
                ('subs', models.IntegerField(choices=[(1, 'Água Mineral'), (2, 'Areia'), (3, 'Areia Lavada'), (4, 'Argila'), (5, 'Calcário'), (6, 'Granito'), (7, 'Ouro')])),
                ('uso', models.IntegerField(choices=[(0, 'Não Informado'), (1, 'Construção Civil'), (2, 'Corretivo de solo'), (3, 'Industrial')])),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('cidades_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.cidades')),
                ('pessoa_fisica_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.pessoa_fisica')),
                ('pessoa_juridica_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.pessoa_juridica')),
            ],
        ),
        migrations.AddField(
            model_name='operacao_empresa',
            name='pessoa_juridica_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.pessoa_juridica'),
        ),
        migrations.AddField(
            model_name='arrecadacao',
            name='cidades_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='map.cidades'),
        ),
    ]
