# Generated by Django 2.1.1 on 2018-12-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20181026_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='demografico',
            name='mes',
            field=models.IntegerField(choices=[(1, 'janeiro'), (2, 'fevereiro'), (3, 'março'), (4, 'abril'), (5, 'maio'), (6, 'junho'), (7, 'julho'), (8, 'agosto'), (9, 'setembro'), (10, 'outubro'), (11, 'novembro'), (12, 'dezembro')], default=1),
        ),
    ]
