# Generated by Django 2.1.1 on 2018-12-10 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20181203_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='cfem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.IntegerField(choices=[(0, 'DADO NÃO CADASTRADO'), (1, 'Quilate'), (2, 'Grama'), (3, 'Quilograma'), (4, 'Litro'), (5, 'Metro cúbico'), (6, 'Tonelada')])),
                ('quantidade', models.FloatField()),
                ('valor', models.FloatField()),
                ('subs', models.IntegerField(choices=[(0, 'DADO NÃO CADASTRADO'), (1, 'AMETISTA'), (2, 'AREIA'), (3, 'AREIA LAVADA'), (4, 'ARENITO'), (5, 'ARGILA'), (6, 'BASALTO'), (7, 'BRITA DE GRANITO'), (8, 'CALCEDÔNIA'), (9, 'CALCÁRIO'), (10, 'CALCÁRIO CALCÍTICO'), (11, 'CALCÁRIO DOLOMÍTICO'), (12, 'CALCÁRIO INDUSTRIAL'), (13, 'CASCALHO'), (14, 'CASCALHO DIAMANTÍFERO'), (15, 'CASSITERITA'), (16, 'CAULIM'), (17, 'CHUMBO'), (18, 'COBRE'), (19, 'COLUMBITA'), (20, 'CONGLOMERADO'), (21, 'DIAMANTE'), (22, 'DIAMANTE INDUSTRIAL'), (23, 'DOLOMITO'), (24, 'ESTANHO'), (25, 'FELDSPATO'), (26, 'FILITO'), (27, 'FOSFATO'), (28, 'GABRO'), (29, 'GALENA'), (30, 'GRANITO'), (31, 'GRANITO ORNAMENTAL'), (32, 'HEMATITA'), (33, 'ILMENITA'), (34, 'LATERITA'), (35, 'MAGNETITA'), (36, 'MANGANÊS'), (37, 'MINÉRIO DE CHUMBO'), (38, 'MINÉRIO DE COBRE'), (39, 'MINÉRIO DE ESTANHO'), (40, 'MINÉRIO DE FERRO'), (41, 'MINÉRIO DE MANGANÊS'), (42, 'MINÉRIO DE NIÓBIO'), (43, 'MINÉRIO DE NÍQUEL'), (44, 'MINÉRIO DE OURO'), (45, 'MINÉRIO DE TITÂNIO'), (46, 'MINÉRIO DE VANDIO'), (47, 'MINÉRIO DE ZINCO'), (48, 'MÁRMORE'), (49, 'NÍQUEL'), (50, 'OURO'), (51, 'QUARTZITO'), (52, 'QUARTZO'), (53, 'SAIBRO'), (54, 'SIENITO'), (55, 'TANTALITA'), (56, 'TITÂNIO'), (57, 'TURFA'), (58, 'TURMALINA'), (59, 'TÂNTALO'), (60, 'ZINCO'), (61, 'ÁGUA MINERAL'), (62, 'ÁGUA POTÁVEL DE MESA'), (63, 'ÁGUAS TERMAIS'), (64, 'ARGILA COMUM'), (65, 'AREIA IN NATURA'), (66, 'GEMA'), (67, 'AREIA QUARTZOSA'), (68, 'CALCÁRIO P/ BRITA'), (69, 'AREIA COMUM'), (70, 'ARGILA P/CER. VERMELH'), (71, 'PEDRA CALCÁRIA'), (72, 'FERRO'), (73, 'SEIXOS ROLADOS'), (74, 'CASCALHO SILICOSO'), (75, 'BASALTO P/ BRITA'), (76, 'GRANITO P/ BRITA'), (77, 'MINÉRIO DE PRATA'), (78, 'OURO NATIVO')])),
                ('ano', models.IntegerField()),
                ('pessoa_fisica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.pessoa_fisica')),
            ],
        ),
        migrations.CreateModel(
            name='tah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorCobrado', models.FloatField()),
                ('valorPago', models.FloatField()),
                ('numProcesso', models.IntegerField()),
                ('anoProcesso', models.IntegerField()),
                ('pessoa_fisica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.pessoa_fisica')),
            ],
        ),
        migrations.RenameField(
            model_name='titulos_minerarios',
            old_name='cidades_id',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='titulos_minerarios',
            old_name='pessoa_fisica_id',
            new_name='pessoa_fisica',
        ),
        migrations.RenameField(
            model_name='titulos_minerarios',
            old_name='pessoa_juridica_id',
            new_name='pessoa_juridica',
        ),
        migrations.RemoveField(
            model_name='operacao_empresa',
            name='pessoa_juridica_id',
        ),
        migrations.RemoveField(
            model_name='pessoa_juridica',
            name='atividade_mineradora',
        ),
        migrations.RemoveField(
            model_name='pessoa_juridica',
            name='cidades_id',
        ),
        migrations.AddField(
            model_name='operacao_empresa',
            name='pessoa_juridica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.pessoa_juridica'),
        ),
        migrations.AlterField(
            model_name='titulos_minerarios',
            name='fase',
            field=models.IntegerField(choices=[(0, 'DADO NÃO CADASTRADO'), (1, 'AUTORIZAO DE PESQUISA'), (2, 'CONCESSO DE LAVRA'), (3, 'DISPONIBILIDADE'), (4, 'LAVRA GARIMPEIRA'), (5, 'LICENCIAMENTO'), (6, 'REGISTRO DE EXTRAO'), (7, 'REQUERIMENTO DE LAVRA'), (8, 'REQUERIMENTO DE LAVRA GARIMPEIRA'), (9, 'REQUERIMENTO DE LICENCIAMENTO'), (10, 'REQUERIMENTO DE PESQUISA'), (11, 'REQUERIMENTO DE REGISTRO DE EXTRAO')]),
        ),
        migrations.AddField(
            model_name='tah',
            name='pessoa_juridica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.pessoa_juridica'),
        ),
        migrations.AddField(
            model_name='tah',
            name='titulos_minerarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.titulos_minerarios'),
        ),
        migrations.AddField(
            model_name='cfem',
            name='pessoa_juridica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.pessoa_juridica'),
        ),
        migrations.AddField(
            model_name='cfem',
            name='titulos_minerarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.titulos_minerarios'),
        ),
    ]
