# Generated by Django 2.1.1 on 2018-12-10 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20181210_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrecadacao',
            old_name='cidades_id',
            new_name='cidades',
        ),
        migrations.RenameField(
            model_name='demografico',
            old_name='cidades_id',
            new_name='cidades',
        ),
        migrations.RenameField(
            model_name='economia',
            old_name='cidades_id',
            new_name='cidades',
        ),
        migrations.RenameField(
            model_name='socioeconomico',
            old_name='cidades_id',
            new_name='cidades',
        ),
    ]
