# Generated by Django 2.1.1 on 2018-12-10 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_auto_20181210_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfem',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='map.cidades'),
        ),
    ]
