# Generated by Django 2.1.1 on 2018-12-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_cfem_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfem',
            name='ano_proc',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cfem',
            name='num_proc',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
