# Generated by Django 2.1.1 on 2019-02-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20181212_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrecadacao',
            old_name='cidades',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='demografico',
            old_name='cidades',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='economia',
            old_name='cidades',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='socioeconomico',
            old_name='cidades',
            new_name='cidade',
        ),
        migrations.AlterField(
            model_name='arrecadacao',
            name='ano',
            field=models.IntegerField(choices=[(2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975), (1974, 1974), (1973, 1973), (1972, 1972), (1971, 1971), (1970, 1970)], default=2019),
        ),
        migrations.AlterField(
            model_name='arrecadacao',
            name='tipo_atv',
            field=models.IntegerField(choices=[(0, '-------'), (1, 'Água Mineral/Potável'), (2, 'Calcário'), (3, 'Calcário Calcítico'), (4, 'Calcário Dolomítico'), (5, 'Água Termal'), (6, 'Granito/Brita'), (7, 'Minério de Manganês'), (8, 'Minério de Ouro/Ouro'), (9, 'Gema/Diamantes'), (10, 'Argila'), (11, 'Areia')], default=1),
        ),
        migrations.AlterField(
            model_name='cfem',
            name='subs',
            field=models.IntegerField(choices=[(0, '---------'), (1, 'AMETISTA'), (2, 'AREIA'), (3, 'AREIA LAVADA'), (4, 'ARENITO'), (5, 'ARGILA'), (6, 'BASALTO'), (7, 'BRITA DE GRANITO'), (8, 'CALCEDÔNIA'), (9, 'CALCÁRIO'), (10, 'CALCÁRIO CALCÍTICO'), (11, 'CALCÁRIO DOLOMÍTICO'), (12, 'CALCÁRIO INDUSTRIAL'), (13, 'CASCALHO'), (14, 'CASCALHO DIAMANTÍFERO'), (15, 'CASSITERITA'), (16, 'CAULIM'), (17, 'CHUMBO'), (18, 'COBRE'), (19, 'COLUMBITA'), (20, 'CONGLOMERADO'), (21, 'DIAMANTE'), (22, 'DIAMANTE INDUSTRIAL'), (23, 'DOLOMITO'), (24, 'ESTANHO'), (25, 'FELDSPATO'), (26, 'FILITO'), (27, 'FOSFATO'), (28, 'GABRO'), (29, 'GALENA'), (30, 'GRANITO'), (31, 'GRANITO ORNAMENTAL'), (32, 'HEMATITA'), (33, 'ILMENITA'), (34, 'LATERITA'), (35, 'MAGNETITA'), (36, 'MANGANÊS'), (37, 'MINÉRIO DE CHUMBO'), (38, 'MINÉRIO DE COBRE'), (39, 'MINÉRIO DE ESTANHO'), (40, 'MINÉRIO DE FERRO'), (41, 'MINÉRIO DE MANGANÊS'), (42, 'MINÉRIO DE NIÓBIO'), (43, 'MINÉRIO DE NÍQUEL'), (44, 'MINÉRIO DE OURO'), (45, 'MINÉRIO DE TITÂNIO'), (46, 'MINÉRIO DE VANDIO'), (47, 'MINÉRIO DE ZINCO'), (48, 'MÁRMORE'), (49, 'NÍQUEL'), (50, 'OURO'), (51, 'QUARTZITO'), (52, 'QUARTZO'), (53, 'SAIBRO'), (54, 'SIENITO'), (55, 'TANTALITA'), (56, 'TITÂNIO'), (57, 'TURFA'), (58, 'TURMALINA'), (59, 'TÂNTALO'), (60, 'ZINCO'), (61, 'ÁGUA MINERAL'), (62, 'ÁGUA POTÁVEL DE MESA'), (63, 'ÁGUAS TERMAIS'), (64, 'ARGILA COMUM'), (65, 'AREIA IN NATURA'), (66, 'GEMA'), (67, 'AREIA QUARTZOSA'), (68, 'CALCÁRIO P/ BRITA'), (69, 'AREIA COMUM'), (70, 'ARGILA P/CER. VERMELH'), (71, 'PEDRA CALCÁRIA'), (72, 'FERRO'), (73, 'SEIXOS ROLADOS'), (74, 'CASCALHO SILICOSO'), (75, 'BASALTO P/ BRITA'), (76, 'GRANITO P/ BRITA'), (77, 'MINÉRIO DE PRATA'), (78, 'OURO NATIVO')]),
        ),
        migrations.AlterField(
            model_name='demografico',
            name='ano',
            field=models.IntegerField(choices=[(2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975), (1974, 1974), (1973, 1973), (1972, 1972), (1971, 1971), (1970, 1970)], default=2019),
        ),
        migrations.AlterField(
            model_name='economia',
            name='ano',
            field=models.IntegerField(choices=[(2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975), (1974, 1974), (1973, 1973), (1972, 1972), (1971, 1971), (1970, 1970)], default=2019),
        ),
        migrations.AlterField(
            model_name='operacao_empresa',
            name='ano',
            field=models.IntegerField(choices=[(2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975), (1974, 1974), (1973, 1973), (1972, 1972), (1971, 1971), (1970, 1970)], default=2019),
        ),
        migrations.AlterField(
            model_name='socioeconomico',
            name='ano',
            field=models.IntegerField(choices=[(2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975), (1974, 1974), (1973, 1973), (1972, 1972), (1971, 1971), (1970, 1970)], default=2019),
        ),
        migrations.AlterField(
            model_name='titulos_minerarios',
            name='ano',
            field=models.IntegerField(choices=[(2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975), (1974, 1974), (1973, 1973), (1972, 1972), (1971, 1971), (1970, 1970)], default=2019),
        ),
        migrations.AlterField(
            model_name='titulos_minerarios',
            name='subs',
            field=models.IntegerField(choices=[(-1, '-------'), (0, 'DADO NÃO CADASTRADO'), (1, 'AMETISTA'), (2, 'AREIA'), (3, 'AREIA LAVADA'), (4, 'ARENITO'), (5, 'ARGILA'), (6, 'BASALTO'), (7, 'BRITA DE GRANITO'), (8, 'CALCEDÔNIA'), (9, 'CALCÁRIO'), (10, 'CALCÁRIO CALCÍTICO'), (11, 'CALCÁRIO DOLOMÍTICO'), (12, 'CALCÁRIO INDUSTRIAL'), (13, 'CASCALHO'), (14, 'CASCALHO DIAMANTÍFERO'), (15, 'CASSITERITA'), (16, 'CAULIM'), (17, 'CHUMBO'), (18, 'COBRE'), (19, 'COLUMBITA'), (20, 'CONGLOMERADO'), (21, 'DIAMANTE'), (22, 'DIAMANTE INDUSTRIAL'), (23, 'DOLOMITO'), (24, 'ESTANHO'), (25, 'FELDSPATO'), (26, 'FILITO'), (27, 'FOSFATO'), (28, 'GABRO'), (29, 'GALENA'), (30, 'GRANITO'), (31, 'GRANITO ORNAMENTAL'), (32, 'HEMATITA'), (33, 'ILMENITA'), (34, 'LATERITA'), (35, 'MAGNETITA'), (36, 'MANGANÊS'), (37, 'MINÉRIO DE CHUMBO'), (38, 'MINÉRIO DE COBRE'), (39, 'MINÉRIO DE ESTANHO'), (40, 'MINÉRIO DE FERRO'), (41, 'MINÉRIO DE MANGANÊS'), (42, 'MINÉRIO DE NIÓBIO'), (43, 'MINÉRIO DE NÍQUEL'), (44, 'MINÉRIO DE OURO'), (45, 'MINÉRIO DE TITÂNIO'), (46, 'MINÉRIO DE VANDIO'), (47, 'MINÉRIO DE ZINCO'), (48, 'MÁRMORE'), (49, 'NÍQUEL'), (50, 'OURO'), (51, 'QUARTZITO'), (52, 'QUARTZO'), (53, 'SAIBRO'), (54, 'SIENITO'), (55, 'TANTALITA'), (56, 'TITÂNIO'), (57, 'TURFA'), (58, 'TURMALINA'), (59, 'TÂNTALO'), (60, 'ZINCO'), (61, 'ÁGUA MINERAL'), (62, 'ÁGUA POTÁVEL DE MESA'), (63, 'ÁGUAS TERMAIS')]),
        ),
    ]
