# Generated by Django 2.1.1 on 2019-03-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_auto_20190205_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socioeconomico',
            name='pop_ocupada',
            field=models.FloatField(null=True),
        ),
    ]
