# Generated by Django 2.1.1 on 2019-04-08 20:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_auto_20190408_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodovias',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326),
        ),
    ]
