# Generated by Django 2.1.1 on 2019-04-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0016_auto_20190408_2035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rodovias',
        ),
    ]
