# Generated by Django 2.1.1 on 2019-04-08 20:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0019_delete_rodovias'),
    ]

    operations = [
        migrations.CreateModel(
            name='rodovias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=12, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('tipo_pavimento', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
    ]
