# Generated by Django 2.1.1 on 2019-05-02 19:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0020_rodovias'),
    ]

    operations = [
        migrations.CreateModel(
            name='aerodromos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('pavimento', models.CharField(default=None, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ferrovias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('situacao', models.CharField(default=None, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='hidrovias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('situacao', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
    ]
