# Generated by Django 2.1.1 on 2019-06-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0021_aerodromos_ferrovias_hidrovias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demografico',
            name='populacao_rural',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='demografico',
            name='populacao_urbana',
            field=models.IntegerField(null=True),
        ),
    ]
