# Generated by Django 2.1.1 on 2019-06-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0022_auto_20190604_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='economia',
            name='pop_ocupada',
        ),
    ]
